### ISSUE TITLE
use local scheduler when PBS_NODEFILE is not available

### ISSUE THREAD

**Issue by Caylo** [hpcugent/vsc-mympirun#106]
right now it causes an error
```
$ mympirun hostname
2017-02-22 17:07:29,771 WARNING    mympirun.IntelHydraMPI_PBS MainThread  set_nodes: failed to get PBS_NODEFILE from environment
2017-02-22 17:07:29,772 ERROR      mympirun        MainThread  Main failed
Traceback (most recent call last):
  File "/vscmnt/gent_vulpix/_/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/EGG-INFO/scripts/mympirun", line 123, in main
    instance = getinstance(*instance_options)
  File "/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/vsc/mympirun/factory.py", line 66, in getinstance
    return coupler_class(options=options.options, cmdargs=options.args)
  File "/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/vsc/mympirun/factory.py", line 58, in __init__
    super(Coupler, self).__init__(**kwargs)
  File "/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/vsc/mympirun/mpi/mpi.py", line 310, in __init__
    super(MPI, self).__init__(**kwargs)
  File "/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/vsc/mympirun/rm/sched.py", line 107, in __init__
    self.set_nodes()
  File "/vscmnt/gent_vulpix/_/user/data/gent/vsc413/vsc41353/mympirun-dev/software/vsc-mympirun/dev/lib/python2.7/site-packages/vsc_mympirun-3.4.4-py2.7.egg/vsc/mympirun/rm/pbs.py", line 49, in set_nodes
    self.log.raiseException("set_nodes: failed to get %s from environment"  % nodevar)
  File "/usr/lib/python2.7/site-packages/vsc/utils/fancylogger.py", line 329, in raiseException
    raise exception, message, tb
Exception: set_nodes: failed to get PBS_NODEFILE from environment
```

**Comment by boegel** [comment]
fixed in #109, thanks @Caylo!
