### ISSUE TITLE
mympirun/4.1.6 does not force OpenMpi3 

### ISSUE THREAD

**Issue by hajgato** [hpcugent/vsc-mympirun#155]
```
mympirun --debug -M OpenMpi3  hostname
2019-06-18 13:58:46,612 DEBUG      mympirun.ExtOption MainThread  changed loglevel to DEBUG, previous state: (mympirun.MympirunParser, NOTSET), (mympirun, NOTSET), (mympirun.vsc.utils.missing, NOTSET), (mympirun.MympirunOption, NOTSET), (mympirun.ExtOptionGroup, NOTSET), (mympirun.ExtOption, NOTSET), (mympirun.mympirun.factory, NOTSET), (mympirun.affinity, NOTSET)
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseoptions: options from environment []
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseoptions: options from commandline ['--debug', '-M', 'OpenMpi3', 'hostname']
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  Found options {'help': None, 'impi_fallback': False, 'basepath': None, 'pinmpi': True, 'output_check_fatal': False, 'debugmpi': False, 'impi_mpdbulletproof': False, 'stats': 0, 'dry_run': False, 'ignoreconfigfiles': None, 'hybrid': None, 'sockets_per_node': 0, 'configfiles': None, 'showsched': False, 'showmpi': False, 'impi_daplud': False, 'setmpi': 'OpenMpi3', 'mpirunoptions': None, 'schedtype': None, 'noenvmodules': False, 'logtofile': None, 'debuglvl': 0, 'impi_xrc': False, 'rdma': None, 'ssh': True, 'use_psm': None, 'info': False, 'multi': None, 'output_check_timeout': 3600, 'launcher': None, 'double': False, 'quiet': False, 'variablesprefix': [], 'branchcount': None, 'universe': None, 'debug': True, 'output': None, 'mpdbootverbose': False, 'order': None, 'overridepin': None} args ['hostname']
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  Initialise case sensitive configparser
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: configfiles initially set []
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: configfiles set through commandline None
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: ignoreconfigfiles set through commandline None
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: following files were parsed []
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: following files were NOT parsed []
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: sections (w/o DEFAULT) []
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: no section MAIN
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: no section ('NO', 'SECTION')
2019-06-18 13:58:46,613 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: no section impi
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: going to parse options through cmdline []
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunParser MainThread  Not processing environment for options
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: options from configfile []
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunOption MainThread  parseconfigfiles: parsed values from configfiles: {}
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunOption MainThread  final options: {'help': None, 'impi_fallback': False, 'basepath': None, 'pinmpi': True, 'output_check_fatal': False, 'debugmpi': False, 'impi_mpdbulletproof': False, 'stats': 0, 'dry_run': False, 'ignoreconfigfiles': None, 'hybrid': None, 'sockets_per_node': 0, 'configfiles': None, 'showsched': False, 'showmpi': False, 'impi_daplud': False, 'setmpi': 'OpenMpi3', 'mpirunoptions': None, 'schedtype': None, 'noenvmodules': False, 'logtofile': None, 'debuglvl': 0, 'impi_xrc': False, 'rdma': None, 'ssh': True, 'use_psm': None, 'info': False, 'multi': None, 'output_check_timeout': 3600, 'launcher': None, 'double': False, 'quiet': False, 'variablesprefix': [], 'branchcount': None, 'universe': None, 'debug': True, 'output': None, 'mpdbootverbose': False, 'order': None, 'overridepin': None}
2019-06-18 13:58:46,614 DEBUG      mympirun.MympirunOption MainThread  mympirun has been forced to use OpenMpi3 as MPI flavor
2019-06-18 13:58:46,614 DEBUG      mympirun        MainThread  PATH before stripfake(): /apps/gent/CO7/skylake-ib/software/vsc-install/0.11.2/bin:/apps/gent/CO7/skylake-ib/software/vsc-mympirun/4.1.6/bin/fake:/apps/gent/CO7/skylake-ib/software/vsc-mympirun/4.1.6/bin:/apps/gent/CO7/skylake-ib/software/vsc-base/2.8.3/bin:/apps/leuven/skylake/2018a/software/CUDA/10.1.105:/apps/leuven/skylake/2018a/software/CUDA/10.1.105/bin:/apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin:/apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/19.4/bin:/apps/leuven/bin:/usr/local/bin:/usr/lpp/mmfs/bin:.:/usr/bin:/usr/sbin:/bin:/usr/local/sbin:/opt/ibutils/bin:/opt/puppetlabs/bin
2019-06-18 13:58:46,617 DEBUG      mympirun        MainThread  PATH after stripfake(): /apps/gent/CO7/skylake-ib/software/vsc-install/0.11.2/bin:/apps/gent/CO7/skylake-ib/software/vsc-mympirun/4.1.6/bin:/apps/gent/CO7/skylake-ib/software/vsc-base/2.8.3/bin:/apps/leuven/skylake/2018a/software/CUDA/10.1.105:/apps/leuven/skylake/2018a/software/CUDA/10.1.105/bin:/apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin:/apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/19.4/bin:/apps/leuven/bin:/usr/local/bin:/usr/lpp/mmfs/bin:.:/usr/bin:/usr/sbin:/bin:/usr/local/sbin:/opt/ibutils/bin:/opt/puppetlabs/bin
2019-06-18 13:58:46,618 INFO       mympirun        MainThread  Command mpirun found at /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun
2019-06-18 13:58:46,620 DEBUG      mympirun        MainThread  Checking whether <class 'mpich.MVAPICH2'> (MPI name: MVAPICH2) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,622 DEBUG      mympirun        MainThread  $EBROOTMVAPICH2 not defined, no match for <class 'mpich.MVAPICH2'>
2019-06-18 13:58:46,624 DEBUG      mympirun        MainThread  Checking whether <class 'openmpi.OpenMPI'> (MPI name: OpenMPI) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,625 DEBUG      mympirun        MainThread  $EBROOTOPENMPI not defined, no match for <class 'openmpi.OpenMPI'>
2019-06-18 13:58:46,627 DEBUG      mympirun        MainThread  Checking whether <class 'mpich.MPICH2Hydra'> (MPI name: MPICH2) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,629 DEBUG      mympirun        MainThread  $EBROOTMPICH2 not defined, no match for <class 'mpich.MPICH2Hydra'>
2019-06-18 13:58:46,631 DEBUG      mympirun        MainThread  Checking whether <class 'intelmpi.IntelMPI'> (MPI name: impi) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,632 DEBUG      mympirun        MainThread  $EBROOTIMPI not defined, no match for <class 'intelmpi.IntelMPI'>
2019-06-18 13:58:46,634 DEBUG      mympirun        MainThread  Checking whether <class 'openmpi.OpenMpi3'> (MPI name: OpenMPI) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,636 DEBUG      mympirun        MainThread  $EBROOTOPENMPI not defined, no match for <class 'openmpi.OpenMpi3'>
2019-06-18 13:58:46,637 DEBUG      mympirun        MainThread  Checking whether <class 'mpich.MPICH2'> (MPI name: MPICH2) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,639 DEBUG      mympirun        MainThread  $EBROOTMPICH2 not defined, no match for <class 'mpich.MPICH2'>
2019-06-18 13:58:46,641 DEBUG      mympirun        MainThread  Checking whether <class 'openmpi.OpenMpiOversubscribe'> (MPI name: OpenMPI) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,642 DEBUG      mympirun        MainThread  $EBROOTOPENMPI not defined, no match for <class 'openmpi.OpenMpiOversubscribe'>
2019-06-18 13:58:46,644 DEBUG      mympirun        MainThread  Checking whether <class 'intelmpi.IntelHydraMPIPbsdsh'> (MPI name: impi) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,646 DEBUG      mympirun        MainThread  $EBROOTIMPI not defined, no match for <class 'intelmpi.IntelHydraMPIPbsdsh'>
2019-06-18 13:58:46,648 DEBUG      mympirun        MainThread  Checking whether <class 'intelmpi.IntelHydraMPI'> (MPI name: impi) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,649 DEBUG      mympirun        MainThread  $EBROOTIMPI not defined, no match for <class 'intelmpi.IntelHydraMPI'>
2019-06-18 13:58:46,651 DEBUG      mympirun        MainThread  Checking whether <class 'mpich.MVAPICH2Hydra'> (MPI name: MVAPICH2) matches with /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun...
2019-06-18 13:58:46,653 DEBUG      mympirun        MainThread  $EBROOTMVAPICH2 not defined, no match for <class 'mpich.MVAPICH2Hydra'>
2019-06-18 13:58:46,654 WARNING    mympirun        MainThread  The executable that called mympirun (OpenMpi3) isn't supported, defaulting to /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun
2019-06-18 13:58:46,656 DEBUG      mympirun.MympirunOption MainThread  Found MPI classes [<class 'mpich.MVAPICH2'>, <class 'openmpi.OpenMPI'>, <class 'mpich.MPICH2Hydra'>, <class 'intelmpi.IntelMPI'>, <class 'openmpi.OpenMpi3'>, <class 'mpich.MPICH2'>, <class 'openmpi.OpenMpiOversubscribe'>, <class 'intelmpi.IntelHydraMPIPbsdsh'>, <class 'intelmpi.IntelHydraMPI'>, <class 'mpich.MVAPICH2Hydra'>]
2019-06-18 13:58:46,656 DEBUG      mympirun.MympirunOption MainThread  Found Sched classes [<class 'slurm.SLURM'>, <class 'local.Local'>, <class 'vsc.mympirun.rm.local.Local'>, <class 'pbs.PBS'>, <class 'scoop.Scoop'>]
2019-06-18 13:58:46,656 WARNING    mympirun.MympirunOption MainThread  No MPI class found that supports scriptname /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun; isfake False). Please use mympirun through one of the direct calls or make sure the mpirun command can be found. Found MPI MVAPICH2, OpenMPI, MPICH2Hydra, IntelMPI, OpenMpi3, MPICH2, OpenMpiOversubscribe, IntelHydraMPIPbsdsh, IntelHydraMPI, MVAPICH2Hydra
2019-06-18 13:58:46,657 ERROR      mympirun        MainThread  Main failed
Traceback (most recent call last):
  File "/vsc-mounts/gent-apps/CO7/skylake-ib/software/vsc-mympirun/4.1.6/lib/python2.7/site-packages/vsc_mympirun-4.1.6-py2.7.egg/EGG-INFO/scripts/mympirun", line 121, in main
    instance_options = get_mpi_and_sched_and_options()
  File "/vsc-mounts/gent-apps/CO7/skylake-ib/software/vsc-mympirun/4.1.6/lib/python2.7/site-packages/vsc_mympirun-4.1.6-py2.7.egg/EGG-INFO/scripts/mympirun", line 100, in get_mpi_and_sched_and_options
    (scriptname, isfake, ", ".join(found_mpi_names)))
  File "build/bdist.linux-x86_64/egg/vsc/utils/fancylogger.py", line 329, in raiseException
    raise exception, message, tb
Exception: No MPI class found that supports scriptname /apps/leuven/skylake/2018a/software/PGI/19.4/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpirun; isfake False). Please use mympirun through one of the direct calls or make sure the mpirun command can be found. Found MPI MVAPICH2, OpenMPI, MPICH2Hydra, IntelMPI, OpenMpi3, MPICH2, OpenMpiOversubscribe, IntelHydraMPIPbsdsh, IntelHydraMPI, MVAPICH2Hydra
```

**Comment by stdweird** [comment]
it's a bug (the passed class via `-M` is passed as a scriptname)
can you try with
`export EBROOTOPENMPI=/abc/OpenMPI/3.1.3-something`
to fake the eb install?

**Comment by hajgato** [comment]
I just installed my own OpenMPI....
