### ISSUE TITLE
vsc-mympirun/5.0.0 does not work with any Python2 code loaded.

### ISSUE THREAD

**Issue by hajgato** [hpcugent/vsc-mympirun#164]
```
 ml foss/2018b Python/2.7.15-foss-2018b vsc-mympirun ; mympirun hostname
Traceback (most recent call last):
  File "/apps/gent/CO7/skylake-ib/software/vsc-mympirun/5.0.0/bin/mympirun", line 14, in <module>
    __import__('pkg_resources').run_script('vsc-mympirun==5.0.0', 'mympirun')
zipimport.ZipImportError: can't decompress data; zlib not available
```

but
```
 ml foss/2018b Python/3.6.6-foss-2018b vsc-mympirun ; mympirun hostname
gligar04.gastly.os
...
```

**Comment by stdweird** [comment]
`zlib` not availabe sounds like an issue with python

it is also a bit strange zlib is called at all, since the setup.py has `zip_safe=False`

**Comment by hajgato** [comment]
I think it is a bit more complicated. We do have `zlib` in Python2, but /usr/bin/python command starts the module python, not the system one. After the py2/py3 hack, zlib is not available anymore (and other stuff missing as well). However, if one removes the module python from the LD_LIBRARY_PATH, then everything works again:
```
[vsc43020@gligar04 ~]$ module purge
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) cluster/victini
[vsc43020@gligar04 ~]$ ml OpenMPI/3.1.3-GCC-8.2.0-2.31.1 Python/2.7.15-GCCcore-8.2.0 vsc-mympirun/5.0.0
[vsc43020@gligar04 ~]$ mympirun hostname
Traceback (most recent call last):
  File "/apps/gent/CO7/skylake-ib/software/vsc-mympirun/5.0.0/bin/mympirun", line 14, in <module>
    __import__('pkg_resources').run_script('vsc-mympirun==5.0.0', 'mympirun')
zipimport.ZipImportError: can't decompress data; zlib not available
[vsc43020@gligar04 ~]$ /usr/bin/python -E
Python 2.7.15 (default, Apr  9 2019, 14:23:31)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[vsc43020@gligar04 ~]$ echo $LD_LIBRARY_PATH
/apps/gent/CO7/skylake-ib/software/vsc-mympirun/5.0.0/lib:/apps/gent/CO7/skylake-ib/software/Python/2.7.15-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/libffi/3.2.1-GCCcore-8.2.0/lib64:/apps/gent/CO7/skylake-ib/software/libffi/3.2.1-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/GMP/6.1.2-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/SQLite/3.27.2-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/Tcl/8.6.9-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/libreadline/8.0-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/ncurses/6.1-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/bzip2/1.0.6-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-eth/software/OpenMPI/3.1.3-GCC-8.2.0-2.31.1/lib:/apps/gent/CO7/skylake-ib/software/hwloc/1.11.11-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/libpciaccess/0.14-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/libxml2/2.9.8-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/XZ/5.2.4-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/numactl/2.0.12-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/zlib/1.2.11-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/binutils/2.31.1-GCCcore-8.2.0/lib:/apps/gent/CO7/skylake-ib/software/GCCcore/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0:/apps/gent/CO7/skylake-ib/software/GCCcore/8.2.0/lib64:/apps/gent/CO7/skylake-ib/software/GCCcore/8.2.0/lib
[vsc43020@gligar04 ~]$ LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -e s/Python/NoPython/` /usr/bin/python
Python 2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[vsc43020@gligar04 ~]$ LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -e s/Python/NoPython/` mympirun hostname
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
gligar04.gastly.os
[vsc43020@gligar04 ~]$
``` 

or 

```
[vsc43020@gligar04 ~]$ python
Python 2.7.15 (default, Apr  9 2019, 14:23:31)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> if 'EBROOTPYTHON' in os.environ:
...     # ebroots excpet mympirun
...     ignore = [v for k,v in os.environ.items() if k.startswith('EBROOT') and not k.endswith('VSCMINMYMPIRUN')]
...     # add realpaths to (sys.path normally ojnly has realpaths)
...     ignore += [os.path.realpath(x) for x in ignore if os.path.exists(x)]
...     # remove sys.path entries that start with eb path
...     sys.path = [x for x in sys.path if not [y for y in ignore if x.startswith(y)]]
...
>>> import zlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named zlib
>>>
[vsc43020@gligar04 ~]$ python
Python 2.7.15 (default, Apr  9 2019, 14:23:31)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>>
[vsc43020@gligar04 ~]$
```

**Comment by hajgato** [comment]
Of course, when you load python3, then `/usr/bin/python` will start system python:
```
[vsc43020@gligar04 ~]$ ml OpenMPI/3.1.3-GCC-8.2.0-2.31.1 Python/3.7.2-GCCcore-8.2.0 vsc-mympirun/5.0.0
[vsc43020@gligar04 ~]$ /usr/bin/python
Python 2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by stdweird** [comment]
`/usr/bin/python` starts the module python? where is that?

**Comment by hajgato** [comment]
What do you mean with this question? I cannot be more specific than this:
```
[vsc43020@gligar04 ~]$ module purge
[vsc43020@gligar04 ~]$ /usr/bin/python --version
Python 2.7.5
[vsc43020@gligar04 ~]$ module load Python/2.7.16-GCCcore-8.3.0
[vsc43020@gligar04 ~]$ /usr/bin/python --version
Python 2.7.16
```

Or am I misunderstand your question?

**Comment by stdweird** [comment]
ouch
i was not aware of this. i'll check what is going on

**Comment by hajgato** [comment]
And if you remove the python part from the `LD_LIBRARY_PATH` then it is OK.
```
[vsc43020@gligar04 ~]$ ml purge
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) cluster/victini
[vsc43020@gligar04 ~]$ /usr/bin/python --version
Python 2.7.5
[vsc43020@gligar04 ~]$ ml Python/2.7.14-foss-2018a
[vsc43020@gligar04 ~]$ /usr/bin/python --version
Python 2.7.14
[vsc43020@gligar04 ~]$ LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -e s/Python/NoPython/g` /usr/bin/python --version
Python 2.7.5
[vsc43020@gligar04 ~]$
```

**Comment by hajgato** [comment]
Additionally, before the `EB_SAFE_HEADER`, you can import zlib, after you cannot (only if a python2 module is loaded).
so with EB_SAFE_HEADER:
```
[vsc43020@gligar04 ~]$ python
Python 2.7.15 (default, Apr  9 2019, 14:23:31)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> if 'EBROOTPYTHON' in os.environ:
...     # ebroots excpet mympirun
...     ignore = [v for k,v in os.environ.items() if k.startswith('EBROOT') and not k.endswith('VSCMINMYMPIRUN')]
...     # add realpaths to (sys.path normally ojnly has realpaths)
...     ignore += [os.path.realpath(x) for x in ignore if os.path.exists(x)]
...     # remove sys.path entries that start with eb path
...     sys.path = [x for x in sys.path if not [y for y in ignore if x.startswith(y)]]
...
>>> import zlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named zlib
```

without EB_SAFE_HEADER:
```
[vsc43020@gligar04 ~]$ python
Python 2.7.15 (default, Apr  9 2019, 14:23:31)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>>
```

**Comment by stdweird** [comment]
@hajgato the fact that `usr/bin/python` does use module loaded python is news for me (and a serious problem). @boegel are you aware of this?

but i'm not sure how it is relevant for mympirun, which shouldn't be using `/usr/bin/python` (unless installed as rpm)

**Comment by hajgato** [comment]
if the `EB_SAFE_HEADER` runs, you cannot `import zlib` anymore.

**Comment by hajgato** [comment]
if you load a python2 module, due to the `EB_SAFE_HEADER` zlib cannot be imported anymore.
As far as I know, EB_SAFE_HEADER was introduced to mympirun work in py2/py3 environment, but as a metter of fact (in our environment) it breaks Python2

**Comment by stdweird** [comment]
it's odd that it breaks it, but probably a bug in the EB_SAFE_HEADER code then.
i can have a quick look if i find the issue

**Comment by hajgato** [comment]
if you import `zlib` before line 3, it works, agter line 11, it does not anymore.
mympirun looks like this:
```
 1 #!/usr/bin/python
  2
  3 import os
  4 import sys
  5 if 'EBROOTPYTHON' in os.environ:
  6     # ebroots excpet mympirun
  7     ignore = [v for k,v in os.environ.items() if k.startswith('EBROOT') and not k.endswith('VSCMINMYMPIRUN')]
  8     # add realpaths to (sys.path normally ojnly has realpaths)
  9     ignore += [os.path.realpath(x) for x in ignore if os.path.exists(x)]
 10     # remove sys.path entries that start with eb path
 11     sys.path = [x for x in sys.path if not [y for y in ignore if x.startswith(y)]]
 12 # EASY-INSTALL-SCRIPT: 'vsc-mympirun==5.0.0','fake/mpirun'
 13 __requires__ = 'vsc-mympirun==5.0.0'
 14 __import__('pkg_resources').run_script('vsc-mympirun==5.0.0', 'fake/mpirun')
```

**Comment by hajgato** [comment]
for some reason, after eb_safe_header, python does not find `lib/python2.7/lib-dynload/` modules, where `zlib` (and others) located.

**Comment by stdweird** [comment]
the code simply throws it all away, that's why it doesn't work anymore
i need to remember what this was supposed to fix, and why i did it like this

**Comment by hajgato** [comment]
I think it was supposed to fix to work in mixed py2/py3 environment. You commented that this part can be omitted when mympirun safely works in py3 environment as well. So I guess, `EB_SAFE_HEADER` have to be run only if python3 module is loaded?

**Comment by hajgato** [comment]
https://github.com/hpcugent/vsc-mympirun/pull/157/files#diff-2eeaed663bd0d25b7e608891384b7298R158

**Comment by stdweird** [comment]
ok, now i see. the module is installed with the `/usr/bin/python` header, and still does the wrong thing somehow (as you pointed out). maybe we should install it with `#!/usr/bin/python -E` as header

**Comment by hajgato** [comment]
I tried, still the same. 
The only thing works: remove python form `LD_LIBRARY_PATH`

**Comment by hajgato** [comment]
```
[vsc43020@gligar04 ~]$ /usr/bin/python -E --version
Python 2.7.5
[vsc43020@gligar04 ~]$ ml Python/2.7.14-foss-2018a
[vsc43020@gligar04 ~]$ /usr/bin/python -E --version
Python 2.7.14
```

**Comment by stdweird** [comment]
ah yes, i missed that part in the output that `-E` doesn't work. i'll first need to understand why system python does pick up module stuff. but the LD_LIBRARY_PATH is probably a clear hint

**Comment by hajgato** [comment]
What  I have figured out to make a wrapper that removes the python from `LD_LIBRARY_PATH`, and then calls `/usr/bin/python mympirun.py`, but thats ugly. There should be a better solution to that.

**Comment by hajgato** [comment]
```
LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -e s/Python/NoPython/g` /usr/bin/python --version
```

**Comment by hajgato** [comment]
so the mympirun binary should be a bash script like this:
```
LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -e s/Python/NoPython/g`
/usr/bin/python path/to/mympirun.py $@
```
or so.

**Comment by hajgato** [comment]
but I am not sure how would that affect mpi parallel python code (as the LD_LIBRARY_PATH is modified....)

**Comment by stdweird** [comment]
i'll make PR

**Comment by stdweird** [comment]
@hajgato see #165, completely untested, but you get the point

**Comment by hajgato** [comment]
will test it tomorrow.
