### ISSUE TITLE
mypmirun fails with OpenMPI 3.x (foss/2019b)

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-mympirun#167]
(note: mypmirun, PMI, not MPI)

```
Traceback (most recent call last):
  File "/apps/gent/CO7/cascadelake-ib/software/vsc-mympirun/5.0.1/lib/python2.7/site-packages/vsc_mympirun-5.0.1-py2.7.egg/vsc/mympirun/main.py", line 117, in main
    instance_options = get_mpi_and_sched_and_options(mpim, mpiopt, schedm)
  File "/apps/gent/CO7/cascadelake-ib/software/vsc-mympirun/5.0.1/lib/python2.7/site-packages/vsc_mympirun-5.0.1-py2.7.egg/vsc/mympirun/main.py", line 94, in get_mpi_and_sched_and_options
    (scriptname, isfake, ", ".join(found_mpi_names)))
  File "/usr/lib/python2.7/site-packages/vsc/utils/fancylogger.py", line 333, in raiseException
    raise err
Exception: No MPI class found that supports scriptname /user/gent/400/vsc40023/eb_scratch/CO7/cascadelake-ib/software/OpenMPI/3.1.4-GCC-8.3.0/bin/mpirun; isfake False). Please use mympirun through one of the direct calls or make sure the mpirun command can be found. Found MPI IntelMPI, OpenMPI4
```

**Comment by boegel** [comment]
fixed in #172
