### ISSUE TITLE
mympirun is not compatible with Python 3.x

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-mympirun#18]
When a Python 3.x module is loaded, `mympirun` can no longer be used because it's not compatible yet with Python 3.x.

**Comment by boegel** [comment]
Ran into a nasty problem, basically because `mympirun` is not compatible with Python 3, only it manifested itself in a weird way (since `mympirun` wasn't actually used, it was only loaded in the environment):

```
$ dask-mpi --help
Traceback (most recent call last):
  File "/apps/gent/CO7/sandybridge/software/distributed/1.21.6-intel-2018a-Python-3.6.4/bin/dask-mpi", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1545, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

Note how `pkg_sources` comes from the system Python 2, while `dask-mpi` is actually being called with `python3` (in shebang)...

```
$ head -1 $(which dask-mpi)
#!/apps/gent/CO7/sandybridge/software/Python/3.6.4-intel-2018a/bin/python
```
